import type { Lang } from './types.ts'

export interface LedgerRow { phase: string; runs: number; minutes: number; usd: number; tiers?: string | null }

/** Time-and-cost table for the issue's ledger comment. */
export const ledgerMarkdown = (rows: LedgerRow[], lang: Lang): string => {
  const t = lang === 'es'
    ? { title: 'Resumen SDD', phase: 'Fase', runs: 'Ejecuciones', tier: 'Nivel', min: 'Min', usd: 'USD', total: 'Total', by: 'generado por el orquestador sdd-factory' }
    : { title: 'SDD summary', phase: 'Phase', runs: 'Runs', tier: 'Tier', min: 'Min', usd: 'USD', total: 'Total', by: 'generated by the sdd-factory orchestrator' }
  const tot = rows.reduce((a, r) => ({ minutes: a.minutes + r.minutes, usd: a.usd + r.usd }), { minutes: 0, usd: 0 })
  const lines = rows.map((r) => `| ${r.phase} | ${r.runs} | ${r.tiers ?? ''} | ${r.minutes.toFixed(1)} | ${r.usd.toFixed(2)} |`)
  return [`### ${t.title}`, '', `| ${t.phase} | ${t.runs} | ${t.tier} | ${t.min} | ${t.usd} |`, '| --- | ---: | --- | ---: | ---: |', ...lines,
    `| **${t.total}** | | | **${tot.minutes.toFixed(1)}** | **${tot.usd.toFixed(2)}** |`, '', `<sub>${t.by}</sub>`].join('\n')
}

/** One line for the PR: totals and a pointer to the issue's ledger comment. */
export const ledgerLine = (rows: { minutes: number; usd: number }[], lang: Lang, repo: string, issue: number): string => {
  const m = rows.reduce((a, r) => a + r.minutes, 0).toFixed(0); const u = rows.reduce((a, r) => a + r.usd, 0).toFixed(2)
  return lang === 'es'
    ? `**SDD:** ${m} min · USD ${u} de agente hasta ahora · detalle por fase en el Issue #${issue} (https://github.com/${repo}/issues/${issue})`
    : `**SDD:** ${m} min · USD ${u} of agent time so far · per-phase detail on issue #${issue} (https://github.com/${repo}/issues/${issue})`
}
