#!/usr/bin/env bash
# The Draft PR linked to an issue ("Closes #N" on the first line of the body). REST only (`gh api`), no GraphQL.
#
#   sdd pr find     <issue>                     → prints the PR number, or nothing
#   sdd pr open     <issue> <branch> <title>    → pushes the branch and opens the Draft PR with "Closes #N"
#   sdd pr ready    <issue>                     → marks the linked PR ready for review (best effort: GitHub has no REST
#                                                  endpoint for it; when the GraphQL call is blocked, says so and exits 0)
#   sdd pr branch   <issue>                     → prints the linked PR's head branch
#   sdd pr scope    <issue>                     → docs | code: docs when every changed file is documentation (docs/**, *.md)
#   sdd pr merge    <issue>                     → squash-merges the linked PR and deletes the branch (Approval Gate 4 granted)
#   sdd pr merged   <issue>                     → exit 0 when the issue has a merged PR ("Closes #N"), prints its number
#   sdd pr view     <issue> [jq]                → the linked PR as JSON (REST `pulls/N`), or one field with a jq filter
#   sdd pr files    <issue>                     → changed files of the linked PR, one per line
#   sdd pr diff     <issue>                     → unified diff of the linked PR
#   sdd pr comments <issue>                     → the PR's comments as text (author, date, body)
#   sdd pr body     <issue> <file|->            → replaces the PR description (the first line must stay "Closes #N")
. "$(dirname "$0")/lib.sh"

cmd="${1:-}"; need_issue "${2:-}"; issue="$2"; r="$(repo)"

closes=".body // \"\" | test(\"(?m)^Closes #$issue\\\\b\")"
find_pr() { gh api "repos/$r/pulls?state=open&per_page=100" --paginate --jq ".[] | select($closes) | .number" | head -1; }
find_merged() { gh api "repos/$r/pulls?state=closed&sort=updated&direction=desc&per_page=100" --paginate --jq ".[] | select(.merged_at != null) | select($closes) | .number" | head -1; }
linked() { n="$(find_pr)"; [ -n "$n" ] || die "no open PR linked to #$issue"; }
comments_text() { gh api "repos/$r/issues/$1/comments?per_page=100" --paginate --jq '.[] | "--- \(.user.login) · \(.created_at)\n\(.body)\n"'; }

case "$cmd" in
  find) find_pr ;;
  merged) n="$(find_merged)"; [ -n "$n" ] && printf '%s\n' "$n" ;;
  branch) linked; gh api "repos/$r/pulls/$n" --jq .head.ref ;;
  view) linked; gh api "repos/$r/pulls/$n" ${3:+--jq "$3"} ;;
  files) linked; gh api "repos/$r/pulls/$n/files?per_page=100" --paginate --jq '.[].filename' ;;
  diff) linked; gh api -H 'Accept: application/vnd.github.diff' "repos/$r/pulls/$n" ;;
  comments) linked; comments_text "$n" ;;
  open)
    branch="${3:-}"; title="${4:-}"; [ -n "$branch" ] && [ -n "$title" ] || die "branch and title required"
    case "$branch" in main|master) die "refusing to open a PR from $branch";; esac
    existing="$(find_pr)"; [ -z "$existing" ] || { printf '%s\n' "$existing"; exit 0; }
    git push -u origin "$branch" >/dev/null 2>&1 || git push -u origin "$branch"
    if [ "$(constitution_lang)" = es ]; then body="$(printf 'Closes #%s\n\n## Resumen\n\n_Generado por sdd-factory; se completa al final de la implementación._\n' "$issue")"
    else body="$(printf 'Closes #%s\n\n## Summary\n\n_Generated by sdd-factory; completed at the end of the implementation._\n' "$issue")"; fi
    gh api -X POST "repos/$r/pulls" -f "title=$title" -f "body=$body" -f "head=$branch" -f "base=$(default_branch)" -F draft=true --jq .number
    ;;
  body)
    linked; f="${3:-}"; [ -n "$f" ] || die "body file required (or '-' to read it from stdin)"
    if [ "$f" = "-" ]; then f="$(mktemp)"; cat > "$f"; trap 'rm -f "$f"' EXIT; fi
    [ -f "$f" ] || die "body file not found: $f"
    head -1 "$f" | grep -Eq "^Closes #$issue\b" || die "the first line of the PR body must stay 'Closes #$issue'"
    gh api -X PATCH "repos/$r/pulls/$n" -F body=@"$f" --jq .number
    ;;
  scope)
    linked
    files="$(gh api "repos/$r/pulls/$n/files?per_page=100" --paginate --jq '.[].filename')"; [ -n "$files" ] || { echo code; exit 0; }
    if printf '%s\n' "$files" | grep -Evq '^(docs/.*|[^/]*\.md|\.github/ISSUE_TEMPLATE/.*\.(yml|md))$'; then echo code; else echo docs; fi
    ;;
  ready)
    linked
    [ "$(gh api "repos/$r/pulls/$n" --jq .draft)" = false ] && { printf '%s\n' "$n"; exit 0; }
    # Draft → ready exists only as the GraphQL mutation markPullRequestReadyForReview (no REST endpoint, 2026-09).
    node="$(gh api "repos/$r/pulls/$n" --jq .node_id)"
    if gh api graphql -f query='mutation($id:ID!){ markPullRequestReadyForReview(input:{pullRequestId:$id}) { pullRequest { isDraft } } }' -f id="$node" >/dev/null 2>&1; then
      printf '%s\n' "$n"
    else
      printf 'sdd: PR #%s stays a draft: GitHub offers no REST endpoint to mark it ready and the GraphQL call failed (blocked network or missing scope). A person marks it "Ready for review" in the PR page.\n' "$n" >&2
      printf '%s\n' "$n"
    fi
    ;;
  merge)
    linked
    [ "$(gh api "repos/$r/issues/$issue" --jq '.type.name // empty')" = Constitution ] && [ "${SDD_ALLOW_CONSTITUTION_MERGE:-}" != 1 ] && die "a Constitution issue is merged by a person, never by the factory"
    branch="$(gh api "repos/$r/pulls/$n" --jq .head.ref)"
    gh api -X PUT "repos/$r/pulls/$n/merge" -f merge_method=squash --jq '.merged' | grep -qx true || die "merge of PR #$n was not accepted (checks pending, conflicts or branch protection)"
    gh api -X DELETE "repos/$r/git/refs/heads/$(urlenc "$branch")" >/dev/null 2>&1 || true
    printf '%s\n' "$n" ;;
  *) sed -n '2,15p' "$0"; exit 1 ;;
esac
